import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Lucas Hoggan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <nav>
          <h1 className="title-text">Lucas Hoggan</h1>
        </nav>
        <div className="section">
          <h2 className="header">Who i am.</h2>
          <div className="divider"></div>
          <div className="row">
            <p className="paragraph">Hi there! My name is Lucas and I am a 14 year old freelance developer. In my free time, I enjoy staying active and healthy by playing rugby and hitting the gym. I am passionate about technology and love using my skills to create and build new projects. I am always looking for new opportunities to challenge myself and expand my knowledge in the field of development, I am based in central Scotland. Thank you for visiting my website</p>
            <img id="home-page-good-photo-1" src="/good-photo-1.jpg"/>
          </div>
        </div>
        <footer>
          <div className="column">
            <h3 className="header">My Social Media</h3>
            <a target="_blank" href="https://www.facebook.com/profile.php?id=100076263414741" className="social">Facebook</a>
            <a target="_blank" href="https://twitter.com/lucashoggan" className="social">Twitter</a>
            <a target="_blank" href="https://www.instagram.com/lucashoggan08/" className="social">Instagram</a>
          </div>
        </footer>
      </main>
    </>
  )
}
